config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :restaurants do
    resources :reviews, only: [:create]
  end

  get '/' => 'restaurants#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end


# Prefix Verb   URI Pattern                     Controller#Action
# restaurants GET    /restaurants(.:format)          restaurants#index    --> if you go to restaurants, a view from index file in restaurants directory will be shown.
#        POST   /restaurants(.:format)          restaurants#create
# new_restaurant GET    /restaurants/new(.:format)      restaurants#new
# edit_restaurant GET    /restaurants/:id/edit(.:format) restaurants#edit
# restaurant GET    /restaurants/:id(.:format)      restaurants#show
#        PATCH  /restaurants/:id(.:format)      restaurants#update
#        PUT    /restaurants/:id(.:format)      restaurants#update
#        DELETE /restaurants/:id(.:format)      restaurants#destroy
# MacBook-Air-Kot:FoodOnRailsBeta2 kotpsot bin/rails server

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews
  validates :name, presence: true
  validates :description, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :score, inclusion: { in: [1,2,3,4,5] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def new
    @restaurant = Restaurant.new # get request, for the /new view
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:notice] = "#{@restaurant.name} saved"
      redirect_to @restaurant
    else
      messages = ""
      @restaurant.errors.full_messages.each do |message|
        messages += message
      end
      flash[:notice] = messages
      render :new
    end
  end

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find params[:id]
    @average = count_average(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find params[:id]
    @restaurant.destroy
    flash[:notice] = "The restaurant was deleted."
    redirect_to '/'
  end

  def edit
    @restaurant = Restaurant.find params[:id]
  end

  def update
    @restaurant = Restaurant.find params[:id]
    if @restaurant.update_attributes(restaurant_params)
      flash[:notice] = "The restaurant was updated."
      redirect_to @restaurant
    else
      render :edit
    end
  end

  def count_average(restaurant)
    @reviews = restaurant.reviews
    @score_counter = 0
    length = @reviews.length
    if length == 0 || length == nil then
      @average = 0.0
    else
      @reviews.each do |rev|
        @score_counter += rev.score.to_f
      end
      @average = @score_counter / length
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :description)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create # standard method - do not rename :)
    restaurant = Restaurant.find(params[:restaurant_id])
    review = Review.new(review_params)
    review.save
    if review.errors.messages.length == 1
      restaurant.reviews << review
      flash[:notice] = "Thanks #{review[:author]}, review has been saved"
    else
      flash[:notice] = "You must submit a score for your review"
    end
    redirect_to restaurant_path(restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:author, :text, :score)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodOnRailsBeta2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_footer.html.erb
<div class="footer"> <a href="https://github.com/Kotauror/FoodOnRailsMakers" class="partial_link">Food On Rails - visit our repo!</a> </div>
</body>
</html>

app/views/restaurants/_header.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag "general_style" %>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <meta charset="utf-8">
    <title>Food on Rails</title>
  </head>
  <body>
    <div class="welcome"> <a href="/restaurants" class="partial_link">Food on Rails - a Rails application for Food</a> </div>

app/views/restaurants/edit.html.erb
<%= render 'header' %>
<%= form_for(@restaurant) do |form| %>
 <p>
   <%= form.label :description %><br/>
   <%= form.text_area :description %>
 </p>
<%= form.submit %>
<% end %>
<%= render 'footer' %>

app/views/restaurants/index.html.erb
<%= render 'header' %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<a href="/restaurants/new" class="new_rest_link"><button class="new_res">Create a new Restaurant</button></a>
<a href="/users/sign_up" class="new_rest_link">Register</a>
<div class="restaurants">
  <% for restaurant in @restaurants do %>
  <div class="single_restaurant">
    <div class="restaurant_name"> <h2><%= link_to restaurant.name, restaurant_path(restaurant), :class => "restaurant_name_link"  %></h2> </div>
    <div class="restaurant_description"> <p> <%= restaurant.description %> </p> </div>
  <!--  <div class="restaurant_rating"> <p> Rating: <%= @average = restaurant.reviews.average(:score).to_f.round(1) %> </p> </div> -->
    <div class="stars"> <p> <% if @average < 1 %>
      <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/0_stars.svg/535px-0_stars.svg.png" width="100px">
      <% elsif @average < 2 %>
      <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/1_stars.svg/535px-1_stars.svg.png" width="100px">
      <% elsif @average < 3 %>
      <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/2_stars.svg/535px-2_stars.svg.png" width="100px">
      <% elsif @average < 4 %>
      <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/3_stars.svg/535px-3_stars.svg.png" width="100px">
      <% elsif @average < 4.5 %>
      <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/4_stars.svg/535px-4_stars.svg.png" width="100px">
      <% elsif @average >= 4.5 %>
      <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/5_stars.svg/535px-5_stars.svg.png" width="100px">
    <% end %>
    </div>
  </div>
  <% end %>
</div>
<%= render 'footer' %>

app/views/restaurants/new.html.erb
<%= render 'header' %>
<div class="notice">
  <%= notice %>
</div>

<%= form_for(@restaurant) do |form| %>
  <p>
    <%= form.label :name %><br/>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :description %><br/>
    <%= form.text_area :description %>
  </p>

  <%= form.submit %>
<% end %>
<%= render 'footer' %>

app/views/restaurants/show.html.erb
<%= render 'header' %>
<div class="notice">
  <%= notice %>
</div>
<div class="everything">
  <div class="restaurant_data">
    <h2><%= @restaurant.name %></h2>
    <p><%= @restaurant.description %></p>
    <p>Average score:
      <%= @average.to_f.round(1) %></p>

  <h3>Add your review</h3>
  <%= form_for([@restaurant, Review.new]) do |form| %>
  <p><%= form.label :author %></p>
  <p><%= form.text_field :author %></p>
  <p><%= form.label :text, 'Review' %></p>
  <p><%= form.text_area :text %></p>
  <p><%= form.label :score %></p>
  <p><%= form.select :score, ['Select', '1','2','3','4','5'] %></p>
  <%= form.submit 'submit' %>
  <% end  %>
  <br><br>

    <%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
    <%= link_to 'Delete', restaurant_path(@restaurant), :method => :delete, data: {:confirm => "Are you sure?"} %>

  </div>

  <div class="reviews">
    <% if @reviews %>
      <h2>Reviews</h2>
      <% for review in @reviews do %>
        <p>
          <strong><%= review.author %></strong>
          :
          <%= review.text %>
          <%= review.score %>/5</p>
      <% end %>
    <% end %>
  </div>
</div>

<%= render 'footer' %>